name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: "on"
      COLORTERM: "truecolor"
      COLORFGBG: "7;0"
      TERM: "xterm-256color"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Download Go modules
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./...
        if: matrix.os != 'windows-latest'

  govulncheck:
    uses: charmbracelet/meta/.github/workflows/govulncheck.yml@main
    with:
      go-version: stable

  semgrep:
    uses: charmbracelet/meta/.github/workflows/semgrep.yml@main

  ruleguard:
    uses: charmbracelet/meta/.github/workflows/ruleguard.yml@main
    with:
      go-version: stable
